物理上描述系统总能量（动能+势能）  
本征值对应系统可能的测量结果  
厄米矩阵（共轭转置等于自身）（so本征值为实数，本征态正交归一构成一组基）

In [2]:
import torch

import quairkit as qkit
from quairkit.core.hamiltonian import *
from quairkit.database.hamiltonian import *
from quairkit.database.random import *
from quairkit.loss import *

In [3]:
num_qubits = 3  # initial setting with 3 qubits
split_line = '\n' + '-' * 100 + '\n'  # a line of '-' for better readability

gamma = torch.ones(num_qubits, num_qubits) * 0.5
beta = torch.ones(num_qubits) * 0.3
H = ising_hamiltonian(gamma, beta)
print("The Pauli decomposition of the Hamiltonian for the Ising model is:\n", H, end=split_line)

gamma = torch.ones(2, num_qubits, num_qubits) * 0.5
H = xy_hamiltonian(gamma)
print("The Pauli decomposition of the Hamiltonian for the XY chain is:\n", H, end=split_line)

gamma = torch.ones(3, num_qubits, num_qubits) * 0.5
H = heisenberg_hamiltonian(gamma)
print("The Pauli decomposition of the Hamiltonian for the Heisenberg model is:\n", H, end=split_line)

H = random_hamiltonian_generator(num_qubits)
print("The Pauli decomposition of the random Hamiltonian is:\n", H, end=split_line)


The Pauli decomposition of the Hamiltonian for the Ising model is:
 0.5 Z0, Z1
0.5 Z0, Z2
0.5 Z1, Z2
0.30000001192092896 X0
0.30000001192092896 X1
0.30000001192092896 X2
----------------------------------------------------------------------------------------------------
The Pauli decomposition of the Hamiltonian for the XY chain is:
 0.5 X0, X1
0.5 Y0, Y1
0.5 X0, X2
0.5 Y0, Y2
0.5 X1, X2
0.5 Y1, Y2
----------------------------------------------------------------------------------------------------
The Pauli decomposition of the Hamiltonian for the Heisenberg model is:
 0.5 X0, X1
0.5 Y0, Y1
0.5 Z0, Z1
0.5 X0, X2
0.5 Y0, Y2
0.5 Z0, Z2
0.5 X1, X2
0.5 Y1, Y2
0.5 Z1, Z2
----------------------------------------------------------------------------------------------------
The Pauli decomposition of the random Hamiltonian is:
 -0.5870752359092613 Y0, X2
-0.891537442403006 Y0
----------------------------------------------------------------------------------------------------


In [4]:
h_list = [[0.1, "X0,Z1"], [0.3, "Z1"], [0.5, "Z2"]]

print(
    "For given Hamiltonian coefficients, "
    "the coresponding Hamiltonian class is:\n",
    Hamiltonian(h_list),
)

For given Hamiltonian coefficients, the coresponding Hamiltonian class is:
 0.1 X0, Z1
0.3 Z1
0.5 Z2


In [ ]:
rho = random_state(num_qubits)
print('Expection value of the Hamiltonian:', rho.expec_val(H), end=split_line)
#量子态ρ在哈密顿量H下的期望值 ⟨H⟩=Tr(ρH)=\sum p <φ|H|φ》（如以概率 p 处于 |φ⟩ ）

exp_H = ExpecVal(H)
print('Expection value of the Hamiltonian:', exp_H(rho))

Expection value of the Hamiltonian: tensor(-0.1891)
----------------------------------------------------------------------------------------------------
Expection value of the Hamiltonian: tensor(-0.1891)


In [6]:
rho = random_state(num_qubits, size=10)  # 1000 random 3-qubit states

print(
    "For 1000 random 3-qubit states, "
    "a set of Expection value of a given Hamiltonian:\n",
    rho.expec_val(H),
    end=split_line,
)
# this is equivalent to below code
# list_exp_H = []
# for i in range(len(rho)):
#     list_exp_H.append(rho[i].expec_val(H))
# list_exp_H = torch.stack(list_exp_H)

exp_H = ExpecVal(H)
print(
    "For 1000 random 3-qubit states, "
    "a set of Expection value of a given Hamiltonian:\n",
    exp_H(rho),
)
# this is equivalent to below code
# exp_H = ExpecVal(H)
# list_exp_H = []
# for i in range(len(rho)):
#     list_exp_H.append(exp_H(rho[i]))
# list_exp_H = torch.stack(list_exp_H)

For 1000 random 3-qubit states, a set of Expection value of a given Hamiltonian:
 tensor([-0.0719,  0.4139, -0.0500,  0.2628,  0.2197, -0.1067,  0.3284, -0.2297,
        -0.3028, -0.2137])
----------------------------------------------------------------------------------------------------
For 1000 random 3-qubit states, a set of Expection value of a given Hamiltonian:
 tensor([-0.0719,  0.4139, -0.0500,  0.2628,  0.2197, -0.1067,  0.3284, -0.2297,
        -0.3028, -0.2137])


哈密顿量 H 是一个厄米算子（Hermitian operator）（满足 $H^\dagger = H$共轭转置），其核心物理意义是描述量子系统的总能量。  
对于孤立系统，时间演化算子 $U(t)$ 由哈密顿量 H 决定，满足：$U(t) = e^{-i H t / \hbar}$  
n 个量子比特的态空间是 $2^n$ 维。    
而哈密顿量作为描述系统能量的算子，其矩阵形式的维度与态空间一致：n 个量子比特的哈密顿量是 $2^n \times 2^n$ 的矩阵


In [ ]:
H = random_hamiltonian_generator(num_qubits)
print("The Pauli decomposition of the random Hamiltonian is:\n", H, end=split_line)
#H输出泡利分解形式
print('Number of terms:', H.n_terms, #总项数
      end=split_line)

print('The Pauli string corresponding to the Hamiltonian:\n', H.pauli_str, #泡利算符组合
      end=split_line)

print('The coefficients of the terms in the Hamiltonian:\n', H.coefficients, #系数
      end=split_line)

print('The matrix form of the Hamiltonian:\n', H.matrix, #哈密顿量的矩阵表示
      end=split_line)

print('The Pauli word of each term:', H.pauli_words,
      #泡利算符组合的结构化表示，通常为整数或编码数组 
      end=split_line)

print('Number of qubits in the Hamiltonian:', H.n_qubits, 
      #哈密顿量所1描述的量子比特总数
      end=split_line)

The Pauli decomposition of the random Hamiltonian is:
 0.4439691692044192 Y0
0.9188369647731893 Z0
0.034091717729002324 Y2
----------------------------------------------------------------------------------------------------
Number of terms: 3
----------------------------------------------------------------------------------------------------
The Pauli string corresponding to the Hamiltonian:
 [[0.4439691692044192, 'Y0'], [0.9188369647731893, 'Z0'], [0.034091717729002324, 'Y2']]
----------------------------------------------------------------------------------------------------
The coefficients of the terms in the Hamiltonian:
 [0.4439691692044192, 0.9188369647731893, 0.034091717729002324]
----------------------------------------------------------------------------------------------------
The matrix form of the Hamiltonian:
 tensor([[ 0.9188+0.0000j,  0.0000-0.0341j,  0.0000+0.0000j,  0.0000+0.0000j,
          0.0000-0.4440j,  0.0000+0.0000j,  0.0000+0.0000j,  0.0000+0.0000j],
        [