In [1]:
import torch

import quairkit as qkit
from quairkit import Hamiltonian, to_state
from quairkit.qinfo import *
from quairkit.database import *

各向同性态  
一种混合态，形式为 $\rho = \frac{1 - p}{d^2} I \otimes I + \frac{p}{d} \sum_{i=1}^d |i\rangle\langle i| \otimes |i\rangle\langle i|$    
prob控制混合程度  
prob = 0：退化为最大混合态（$\rho = \frac{1}{d^2} I \otimes I$ ）    
prob = 1：退化为纯态（$\rho = \frac{1}{d} \sum |i\rangle\langle i| \otimes |i\rangle\langle i|$ ，当 $d=2$ 时是贝尔态的混合形式 ）

In [2]:
num_qubits = 2  # set the number of qubits

# 制备零态 |00⟩
state = zero_state(num_qubits)  
print(f"zero states with 2 qubits: {state}")

# 制备贝尔态 (|00⟩ + |11⟩)/√2
state = bell_state(num_qubits)  
print(f"Bell states: {state}")

# 制备各向同性态（isotropic state）
state = isotropic_state(num_qubits, prob=0.1)  
print(f"isotropic state: {state}")

zero states with 2 qubits: 
-----------------------------------------------------
 Backend: state_vector
 System dimension: [2, 2]
 System sequence: [0, 1]
[1.+0.j 0.+0.j 0.+0.j 0.+0.j]
-----------------------------------------------------

Bell states: 
-----------------------------------------------------
 Backend: state_vector
 System dimension: [2, 2]
 System sequence: [0, 1]
[0.71+0.j 0.  +0.j 0.  +0.j 0.71+0.j]
-----------------------------------------------------

isotropic state: 
-----------------------------------------------------
 Backend: density_matrix
 System dimension: [2, 2]
 System sequence: [0, 1]
[[0.27+0.j 0.  +0.j 0.  +0.j 0.05+0.j]
 [0.  +0.j 0.22+0.j 0.  +0.j 0.  +0.j]
 [0.  +0.j 0.  +0.j 0.22+0.j 0.  +0.j]
 [0.05+0.j 0.  +0.j 0.  +0.j 0.27+0.j]]
-----------------------------------------------------



backend表示形式   
系统维度  
qubit的索引  
态数据

In [ ]:
#随机态生成  
#rank = 1，纯态，密度矩阵，等价于态矢量
#is_real=True：生成 实系数量子态（态矢量或密度矩阵的元素为实数 ）
#size批量态
state = random_state(num_qubits, rank=1)  
state = random_state(num_qubits, is_real=True) 
state = random_state(num_qubits, size=1000)  

to_state 用于将 PyTorch Tensor 或 NumPy 数组转换为 State 对象，自动识别输入  
输入是一维张量（如 [d] ）或二维张量但某一维为 1（如 [d, 1] ）→ 识别为态矢量。  
输入是二维方阵（如 [d, d] ）→ 识别为密度矩阵

In [ ]:
data = haar_state_vector(
    num_qubits
)  #  生成 Haar 随机态矢量（2 比特）
state = to_state(data)
print(f"A state vector with 2 qubits following Haar random{state}")

# 生成随机密度矩阵（2 比特）
data = random_density_matrix(num_qubits)  # random 2-qubit density matrix
state = to_state(data)
print(f"type of the state: {state.backend}")

A state vector with 2 qubits following Haar random
-----------------------------------------------------
 Backend: state_vector
 System dimension: [2]
 System sequence: [0]
[-0.47+0.2j  -0.16+0.85j]
-----------------------------------------------------

type of the state: density_matrix


In [5]:
# 1bit的批量纯态
state = random_state(num_qubits=1, rank=1, size=3)  # 3 random single-qubit pure states
print(f"3 random single-qubit pure states: {state}")

3 random single-qubit pure states: 
-----------------------------------------------------
 Backend: state_vector
 System dimension: [2]
 System sequence: [0]
 Batch size: [3]

 # 0:
[-0.66+0.48j -0.02-0.58j]
 # 1:
[-0.33+0.89j -0.15+0.26j]
 # 2:
[-0.53+0.82j  0.12-0.18j]
-----------------------------------------------------



纯态的密度矩阵是 $\rho = |\psi\rangle\langle\psi|$

In [ ]:

print("Its density matrix is :\n", state.density_matrix)
#ket右矢∣ψ⟩
print("\nIts ket is :\n", state.ket)
#左矢⟨ψ∣
print("\nIts bra is :\n", state.bra)

Its density matrix is :
 tensor([[[ 0.6667+0.0000j, -0.2629-0.3913j],
         [-0.2629+0.3913j,  0.3333+0.0000j]],

        [[ 0.9107+0.0000j,  0.2815-0.0456j],
         [ 0.2815+0.0456j,  0.0893+0.0000j]],

        [[ 0.9534+0.0000j, -0.2106+0.0071j],
         [-0.2106-0.0071j,  0.0466+0.0000j]]])

Its ket is :
 tensor([[[-0.6617+0.4784j],
         [-0.0199-0.5770j]],

        [[-0.3319+0.8947j],
         [-0.1474+0.2599j]],

        [[-0.5260+0.8227j],
         [ 0.1223-0.1778j]]])

Its bra is :
 tensor([[[-0.6617-0.4784j, -0.0199+0.5770j]],

        [[-0.3319-0.8947j, -0.1474-0.2599j]],

        [[-0.5260-0.8227j,  0.1223+0.1778j]]])


↓将 State 对象的内部数据（态矢量或密度矩阵 ）转换为 NumPy ndarray 类型

In [7]:
print("\nThe state is :\n", state.numpy())


The state is :
 [[-0.6616574 +0.4784363j  -0.01994713-0.5769838j ]
 [-0.33193117+0.89473677j -0.14735043+0.2599147j ]
 [-0.52599597+0.8226604j   0.12226242-0.17779209j]]


In [ ]:
print("The trace of these states are", state.trace())
print("The rank of these states are", state.rank)
print("The size of these states are", state.dim)
print("The shape of vectorization of these states are", state.vec.shape)
#.vec.shape
# 将密度矩阵按列展开为矢量后的形状
# （用于某些数学变换，如 Choi 表示 ）

The trace of these states are tensor([1.0000+0.j, 1.0000+0.j, 1.0000+0.j])
The rank of these states are 1
The size of these states are 2
The shape of vectorization of these states are torch.Size([3, 4, 1])


In [11]:
# 量子系统的个数（如 1 比特系统是 1 个 ）
print("The number of systems in these states are", state.num_systems)
#判断是否为qubits
print("Are these states qubits?", state.are_qubits())
print("Are these states qutrits?", state.are_qutrits())

The number of systems in these states are 1
Are these states qubits? True
Are these states qutrits? False


↓直接索引，提取批量态中的第 i 个态

In [12]:
print(f"the second and third state in the batch: {state[1:]}")

the second and third state in the batch: 
-----------------------------------------------------
 Backend: state_vector
 System dimension: [2]
 System sequence: [0]
 Batch size: [2]

 # 0:
[-0.33+0.89j -0.15+0.26j]
 # 1:
[-0.53+0.82j  0.12-0.18j]
-----------------------------------------------------



### 量子态操作

内积是密度矩阵乘积的迹，对应纯态的 $\langle\psi|\phi\rangle$（因 state_1 是零态 $|0\rangle\langle0|$，state_2 是随机纯态 $|\phi\rangle\langle\phi|$，乘积的迹为 $\langle0|\phi\rangle\langle\phi|0\rangle = |\langle0|\phi\rangle|^2$ ）

In [ ]:
## 生成 1 比特零态的密度矩阵
state_1 = zero_state(num_qubits=1).density_matrix
# 生成随机密度矩阵并转换为 State 对象
data = random_density_matrix(num_qubits=1)
state_2 = to_state(data).density_matrix
#矩阵乘法
print(f"matrix multiplication:\n{state_1 @ state_2}")
#计算内积

print("The overlap of state_1 and state_2 is :", trace(state_1 @ state_2))

matrix multiplication:
tensor([[ 0.4490+0.0000j, -0.2443+0.3630j],
        [ 0.0000+0.0000j,  0.0000+0.0000j]])
The overlap of state_1 and state_2 is : tensor(0.4490+0.j)


In [14]:
#张量积
product_state = NKron(state_1, state_2)
print(f"tensor product:\n{product_state}")

tensor product:
tensor([[ 0.4490+0.0000j, -0.2443+0.3630j,  0.0000+0.0000j, -0.0000+0.0000j],
        [-0.2443-0.3630j,  0.5510+0.0000j,  0.0000-0.0000j,  0.0000+0.0000j],
        [ 0.0000+0.0000j, -0.0000+0.0000j,  0.0000+0.0000j, -0.0000+0.0000j],
        [ 0.0000-0.0000j,  0.0000+0.0000j,  0.0000-0.0000j,  0.0000+0.0000j]])


系统置换  
修改 system_seq 置换量子态的子系统（如交换 2 比特系统的两个 qubit ）

In [15]:
#生成2bit纯态  
state = random_state(num_qubits=2, rank=1, size=1)  # random 2-qubit pure states
print(f"1 random 2-qubit pure states: {state}")

#交换两个qubit
state.system_seq = [1, 0]  # permutation
print(f"state after permutation: {state}")

1 random 2-qubit pure states: 
-----------------------------------------------------
 Backend: state_vector
 System dimension: [2, 2]
 System sequence: [0, 1]
[0.53+0.02j 0.46+0.42j 0.04-0.16j 0.27+0.49j]
-----------------------------------------------------

state after permutation: 
-----------------------------------------------------
 Backend: state_vector
 System dimension: [2, 2]
 System sequence: [1, 0]
[0.53+0.02j 0.04-0.16j 0.46+0.42j 0.27+0.49j]
-----------------------------------------------------



In [ ]:
## 查看当前态的数据类型和设备
print("The dtype of these states are", state.dtype)
print("The device of these states are", state.device)

## 克隆态并修改数据类型和设备
#clone()：深拷贝量子态，避免原态被修改
#
new_state = state.clone().to(
    dtype=torch.complex128, 
    device="cpu"
)  # change to "cuda" if gpu is available
print("The dtype of new states are", new_state.dtype)
print("The device of new states are", new_state.device)

The dtype of these states are torch.complex64
The device of these states are cpu
The dtype of new states are torch.complex128
The device of new states are cpu


与环境相互作用

In [17]:
#幺正演化
#量子态可通过幺正操作演化，模拟无噪声环境下的时间演化

## 生成 1 比特幺正操作
unitary = random_unitary(num_qubits=1)
#将幺正操作作用于指定子系统
state_evo = state.evolve(unitary, sys_idx=[1])
print(f"state after evolving with unitary: {state_evo}")

state after evolving with unitary: 
-----------------------------------------------------
 Backend: state_vector
 System dimension: [2, 2]
 System sequence: [1, 0]
[-0.48+0.49j -0.13+0.39j -0.41+0.12j -0.29-0.28j]
-----------------------------------------------------



量子态可通过量子信道演化，模拟有噪声环境下的退相干  

纯态的自动转换：纯态通过噪声信道后会变为混合态，ket 和 bra 属性丢失（因混合态无法用单一态矢量表示 ）

In [19]:
# 生成 1 比特随机量子信道（Kraus 表示）
kraus = random_channel(num_qubits=1)
# 应用量子信道（作用于 sys_idx=[0]，Kraus 表示）
state_kra = state.transform(kraus, sys_idx=[0], repr_type="kraus")
print(f"state after transformation: {state}")

state after transformation: 
-----------------------------------------------------
 Backend: state_vector
 System dimension: [2, 2]
 System sequence: [0, 1]
[0.53+0.02j 0.46+0.42j 0.04-0.16j 0.27+0.49j]
-----------------------------------------------------



In [ ]:
#量子信道choi表示作用，同上
choi = random_channel(num_qubits=1, target="choi")
state_cho = state.transform(choi, sys_idx=[1], repr_type="choi")
print(f"state after transformation: {state}")

state after transformation: 
-----------------------------------------------------
 Backend: state_vector
 System dimension: [2, 2]
 System sequence: [0, 1]
[0.53+0.02j 0.46+0.42j 0.04-0.16j 0.27+0.49j]
-----------------------------------------------------



“可观测量（observable）” 指的是能对量子系统进行测量、并得到确定实验结果的物理量（比如自旋、能量、位置等 ）。    
可观测量对应一个厄米算子（Hermitian Operator） 。对量子态进行测量，本质上就是计算这个算子在该量子态下的 “期望值”（ expectation value ）。  
Pauli Z 算子（常简称 Z 算子 ）是单量子比特系统里最基础的可观测量之一，它作用于量子比特的计算基 $|0\rangle$、$|1\rangle$ 时，有明确的操作：$Z|0\rangle = |0\rangle, \quad Z|1\rangle = -|1\rangle$你可以把它理解成 “测量量子比特在 Z 方向的自旋”，测量结果只能是 $+1$（对应 $|0\rangle$ ）或 $-1$（对应 $|1\rangle$ ）  


Hamiltonian 是一个用来 描述 “哈密顿量” 或者 “可观测量集合” 的工具类（虽然名字叫 Hamiltonian，但也常用于构造一般的可观测量 ）  
Hamiltonian([(2, "Z0")]):   
构造一个可观测量，它的 “作用维度” 是 2（对应单 qubit 的 2 维希尔伯特空间 ）    
这个可观测量具体是 “对第 1 个 qubit 施加 Pauli Z 算子”（即 Z0 ）    
后续就可以用 state.expec_val(hamiltonian=observable) 去计算 量子态在这个可观测量下的期望值，也就是测量结果的统计平均值  


↓可观测量：用 Hamiltonian 构造（如 Pauli Z 算子 Z0 作用于第 1 个 qubit ）  
期望值：量子态 $\rho$ 在可观测量 O 下的期望值为 $\text{tr}(\rho O)$，描述测量结果的统计平均  

In [ ]:
# 构造可观测量（Pauli Z 算子作用于第 1 个 qubit）
observable = Hamiltonian([(2, "Z0")])

# 计算量子态在该可观测量下的期望值
print(
    "the expectation value under the given observable: ",
    state.expec_val(hamiltonian=observable),
)

the expectation value under the given observable:  tensor(0.6562)


In [ ]:
# 在 {|0> |1>} 基下测量量子态，返回各基矢的测量概率
print("Theoretical value is :", state.measure())  

Theoretical value is : tensor([0.2787, 0.3854, 0.0276, 0.3084])
