In [1]:
import quairkit as qkit
from quairkit import to_state
from quairkit.database import *
from quairkit.qinfo import *

qkit.set_dtype("complex128")

In [ ]:
#生成U矩阵
A = random_unitary(num_qubits=1)
B = random_unitary(num_qubits=1)
print(f"Matrix A is:\n{A}\n")
print(f"Matrix B is:\n{B}")

Matrix A is:
tensor([[-0.3532+0.5739j, -0.6183-0.4046j],
        [ 0.3256+0.6633j,  0.6129-0.2800j]])

Matrix B is:
tensor([[-0.6200+0.5384j, -0.3405+0.4580j],
        [-0.1587-0.5482j,  0.3924+0.7213j]])


输出trace，直和（直接加），克罗内克积（NKron即张量积），共轭转置，分解单比特幺正矩阵（decomp_1qubit）    
decomp_1qubit(U):将单比特幺正矩阵 U 分解为 Z-Y-Z 旋转角（量子门的标准分解方式 ）：$U = R_z(\gamma) R_y(\beta) R_z(\alpha)$    
输出三个旋转角 $(\alpha, \beta, \gamma)$，便于分析门的物理意义（如绕 Bloch 球的旋转 ）  

In [3]:
print(f"The trace of matrix A is {trace(A)}")

print(f"The direct sum of matrix A and B is: \n{direct_sum(A,B)}\n")

print(f"The tensor product of matrix A and B is: \n{NKron(A,B)}\n")

print(f"The conjugate transpose of matrix A is: \n{dagger(A)}\n")

print(f"The decomposition of single-qubit unitary operator A to Z-Y-Z rotation angles is {decomp_1qubit(A)}")

The trace of matrix A is (0.2597170816027793+0.2938433805173188j)
The direct sum of matrix A and B is: 
tensor([[-0.3532+0.5739j, -0.6183-0.4046j,  0.0000+0.0000j,  0.0000+0.0000j],
        [ 0.3256+0.6633j,  0.6129-0.2800j,  0.0000+0.0000j,  0.0000+0.0000j],
        [ 0.0000+0.0000j,  0.0000+0.0000j, -0.6200+0.5384j, -0.3405+0.4580j],
        [ 0.0000+0.0000j,  0.0000+0.0000j, -0.1587-0.5482j,  0.3924+0.7213j]])

The tensor product of matrix A and B is: 
tensor([[-0.0900-0.5460j, -0.1426-0.3572j,  0.6011-0.0820j,  0.3958-0.1454j],
        [ 0.3706+0.1026j, -0.5526-0.0296j, -0.1237+0.4031j,  0.0492-0.6047j],
        [-0.5589-0.2360j, -0.4146-0.0767j, -0.2293+0.5036j, -0.0804+0.3761j],
        [ 0.3120-0.2837j, -0.3507+0.4951j, -0.2508-0.2916j,  0.4425+0.3322j]])

The conjugate transpose of matrix A is: 
tensor([[-0.3532-0.5739j,  0.3256-0.6633j],
        [-0.6183+0.4046j,  0.6129+0.2800j]])

The decomposition of single-qubit unitary operator A to Z-Y-Z rotation angles is (tensor(-1.008

$\rho = |\psi\rangle\langle\psi|$ ，其中$|\psi\rangle$就是态矢量，也叫ket矢量

In [ ]:
state1 =  random_state(2).density_matrix
#↑生成一个 2 量子比特的随机量子态（默认情况下可能是混合态 
# 或者纯态），并将其转换为密度矩阵形式。
print(f"The first quantum state is:\n {state1}\n")
state2 = random_state(2, rank=1).ket
#.ket：获取该纯态的态矢量（ket）表示。态矢量是描述纯态的简洁方式

print(f"The second quantum state is:\n {state2}")

The first quantum state is:
 tensor([[ 0.0304+0.0000j,  0.0478+0.0518j,  0.0386+0.0041j,  0.0279-0.1071j],
        [ 0.0478-0.0518j,  0.2400+0.0000j, -0.0462-0.0551j, -0.2272-0.1990j],
        [ 0.0386-0.0041j, -0.0462+0.0551j,  0.2199+0.0000j,  0.1542-0.1607j],
        [ 0.0279+0.1071j, -0.2272+0.1990j,  0.1542+0.1607j,  0.5097+0.0000j]])

The second quantum state is:
 tensor([[ 0.4511-0.6282j],
        [-0.1606-0.1444j],
        [ 0.3798-0.2706j],
        [-0.2546-0.2701j]])


态保真度
$F(ρ,σ)=tr( \sqrt{\sqrt{ρ}σ \sqrt{ρ}})^2$
如果其中一个是纯态 $\sigma = |\psi\rangle\langle\psi|$ ，则简化为 $F(\rho,|\psi\rangle\langle\psi|)=\text{tr}(\rho|\psi\rangle\langle\psi|)= \langle\psi|\rho|\psi\rangle$   

Schatten p- 范数
$\|A\|_p = (\text{tr}(|A|^p))^{\frac{1}{p}}$

In [ ]:
#冯・诺依曼熵
'''S(ρ)=−tr(ρ log 2 ρ)衡量量子态的不确定性/混合程度
混合态的熵大于 0，混合程度越高
（越接近最大混合态I/d)，d是希尔伯特空间维度 ），熵越大。
'''
entropy = von_neumann_entropy(state1)
print(f"The von Neumann entropy between state 1 is:\n{entropy}")


#距离迹
'''对于两个量子态的密度矩阵
D(ρ,σ)= 1/2​ ∥ρ−σ∥_1  

state1是混合态密度矩阵，state2若是纯态会先转成密度矩阵
\(\sigma = |\psi\rangle\langle\psi|\)，
然后计算二者差异

衡量两个量子态 “可区分性” 的指标 。
取值范围在[0, 1]，当D = 0时，两个态完全相同；
当D = 1时，两个态完全可区分（比如正交的纯态 ）
'''
traceDistance = trace_distance(state1, state2)
print(traceDistance.dtype)
print(f"The trace distance between state 1 and state 2  is:\n{traceDistance}")


#态保真度
'''
衡量两个量子态 “相似程度” 的指标 。
取值范围在[0, 1]，F = 1表示两个态完全相同（比如同一个纯态 ）；
F = 0表示完全正交、无重叠。
'''
fidelity = state_fidelity(state1, state2)
print(f"The state fidelity between state 1 and state 2 is:\n{fidelity}")


#态的纯度
'''P(ρ)=tr(ρ^2)
也是衡量量子态混合程度的指标  
混合态的纯度在(0, 1)之间，
混合程度越高（越接近最大混合态 ），纯度越接近1/d
纯态的纯度为1，混合态的纯度小于1
'''
purity_state = purity(state1)
print(f"The purity of state 1 is:\n{purity_state}")



#相对熵
'''
于两个量子态的密度矩阵ρ（称为 “被比较态” ）和σ（称为 “参考态” ），
量子相对熵定义为S(ρ||σ)=tr(ρ log ρ) - tr(ρ log σ)  
衡量两个量子态之间 “信息差异” 的指标 ，
可理解为从σ到ρ所需的 “信息增益”
'''
r_entropy = relative_entropy(state1, state2)
print(f"The relative entropy of state 1 and state 2 is:\n{r_entropy}")


# Schatten p-范数
'''
是矩阵范数的一种推广，
用于衡量矩阵 “大小” 或 “能量” 在p阶意义下的度量 。
'''
p = 2
pnorm = p_norm(state1, p)
print(f"The Schatten {p}-norm of state 1 is:\n{pnorm}")

The von Neumann entropy between state 1 is:
0.6949619944161356
torch.float64
The trace distance between state 1 and state 2  is:
0.9689533139196945
The state fidelity between state 1 and state 2 is:
0.22642644586824417
The purity of state 1 is:
0.6960509823055496
The relative entropy of state 1 and state 2 is:
50.772247898589676
The Schatten 2-norm of state 1 is:
0.8342966992057137


验证矩阵 / 量子态的合法性

In [9]:
#检验半正定
is_positive(A)
print(f"The matrix is a positive matrix: {is_positive(A)}")

#检验Positive Partial Transpose
#PPT 是判断两体量子态 “可分离性（非纠缠）” 的充分条件
# （对某些态是必要条件 ）。若返回 False，态可能是纠缠的；
# 若返回 True，态一定是可分离的（非纠缠 ）。
is_ppt(state1)
print(f"The state 1 is a PPT state: {is_ppt(state1)}")

#检验Unitary
is_unitary(A)
print(f"The matrix is a unitary matrix: {is_unitary(A)}")

The matrix is a positive matrix: False
The state 1 is a PPT state: False
The matrix is a unitary matrix: True


三种输入格式  
PyTorch Tensor：深度学习框架常用格式，适合 GPU 加速    
NumPy ndarray：科学计算常用格式，简单易用   
State 对象：QuAIRKit 自定义的量子态对象，包含额外元数据（如系统维度、批次信息 ）  

In [ ]:
# torch.tensor
print(f"State fidelity dtype (torch.tensor): {type(state_fidelity(state1, state2))}")

# numpy.ndarray
state1_num = state1.numpy()
state2_num = state2.numpy()
print(f"State fidelity dtype (numpy.ndarray): {type(state_fidelity(state1_num, state2_num))}")

# State
state1_sta = to_state(state1)
state2_sta = to_state(state2)
print(f"State fidelity dtype (State): {type(state_fidelity(state1_sta, state2_sta))}")

State fidelity dtype (torch.tensor): <class 'torch.Tensor'>
State fidelity dtype (numpy.ndarray): <class 'numpy.ndarray'>
State fidelity dtype (State): <class 'torch.Tensor'>
